# Generated by Django 5.1.7 on 2025-04-04 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterUniqueTogether(
            name='examline',
            unique_together={('subject', 'number')},
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='task',
            name='exam_line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.examline', verbose_name='Линия экзамена'),
        ),
        migrations.AddField(
            model_name='task',
            name='exam_part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.exampart', verbose_name='Часть экзамена'),
        ),
        migrations.AddField(
            model_name='task',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.source', verbose_name='Источник'),
        ),
        migrations.AddField(
            model_name='task',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.subtopic', verbose_name='Подтема задания'),
        ),
        migrations.AddField(
            model_name='solutionimage',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_images', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='generatedvariant',
            name='tasks',
            field=models.ManyToManyField(related_name='variants', to='tasks.task', verbose_name='Задания'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='Задание'),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.topic', verbose_name='Тема задания'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='tasks.topic', verbose_name='Тема'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'task')},
        ),
    ]
