# Generated by Django 5.1.7 on 2025-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='formula_image',
            field=models.ImageField(blank=True, null=True, upload_to='formula_images/', verbose_name='Изображение формулы'),
        ),
        migrations.AddField(
            model_name='task',
            name='latex_formula_svg',
            field=models.TextField(blank=True, null=True, verbose_name='LaTeX-формула в SVG'),
        ),
        migrations.AddField(
            model_name='task',
            name='solution_text_svg',
            field=models.TextField(blank=True, null=True, verbose_name='Решение в SVG'),
        ),
        migrations.AddField(
            model_name='task',
            name='text_svg',
            field=models.TextField(blank=True, null=True, verbose_name='Текст задания в SVG'),
        ),
    ]
