# Generated by Django 5.1.7 on 2025-05-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_formula_image_task_latex_formula_svg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='URL страницы')),
                ('visit_count', models.PositiveIntegerField(default=0, verbose_name='Количество посещений')),
                ('last_visited', models.DateTimeField(auto_now=True, verbose_name='Последнее посещение')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Бот')),
            ],
            options={
                'verbose_name': 'Посещение страницы',
                'verbose_name_plural': 'Посещения страниц',
                'indexes': [models.Index(fields=['url'], name='tasks_pagev_url_35a95e_idx')],
            },
        ),
    ]
